### ISSUE TITLE
P2P Staking validator on statelessnet

### ISSUE THREAD

**Issue by p2pStaking** [near/stakewars-iv#10]
### How many nodes do you plan to run?
 1 node / validator 

*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?

Already validator on mainnet, I want to help and master coming features.

### What region(s) do you plan to run on?
 
France.

**Comment by p2pStaking** [comment]
Done 

```
signer_id:    p2pstaking.statelessnet
receiver_id:  pool.statelessnet
actions:
   -- function call:      
                   method name:  create_staking_pool
                   args:         {
                                   "owner_id": "p2pstaking.statelessnet",
                                   "reward_fee_fraction": {
                                     "denominator": 100,
                                     "numerator": 10
                                   },
                                   "stake_public_key": "ed25519:A6V147BLsrygoBhB4HsvbMozp7DQ536hEnpTcMK1BRq7",
                                   "staking_pool_id": "p2pstaking"
                                 }
                   gas:          230.0 Tgas
                   deposit:      55 NEAR


Your transaction was signed successfully.
Public key: ed25519:A6V147BLsrygoBhB4HsvbMozp7DQ536hEnpTcMK1BRq7
Signature: ed25519:LVukg3ireDr6PUcLMzD5Jz5RrxFU4QmjZNzq7fMf3DQmt8geL15bzAUpXFqMdKU6JufkwKYnB3azWkTSHawkgFc
Transaction sent ...
--- Logs ---------------------------
Logs [pool.statelessnet]:   No logs
Logs [p2pstaking.pool.statelessnet]:   No logs
Logs [p2pstaking.pool.statelessnet]:   No logs
Logs [p2pstaking.statelessnet]:   No logs
Logs [p2pstaking.pool.statelessnet]:   No logs
Logs [p2pstaking.statelessnet]:   No logs
Logs [p2pstaking.statelessnet]:   No logs
Logs [pool.statelessnet]:
  The staking pool @p2pstaking.pool.statelessnet was successfully created. Whitelisting...
Logs [whitelist.statelessnet]:   No logs
Logs [p2pstaking.statelessnet]:   No logs
Logs [p2pstaking.statelessnet]:   No logs
Logs [p2pstaking.statelessnet]:   No logs
--- Result -------------------------
true
------------------------------------

The "create_staking_pool" call to <pool.statelessnet> on behalf of <p2pstaking.statelessnet> succeeded.
Transaction ID: 61ys3arGQydREhKCiV9nEAYwjPvXHevs6R9SrYkajsg5
To see the transaction in the transaction explorer, please open this url in your browser:
https://rpc.statelessnet.near.org/61ys3arGQydREhKCiV9nEAYwjPvXHevs6R9SrYkajsg5
```

**Comment by telezhnaya** [comment]
Hey @p2pStaking !
Congrats, `p2pstaking.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/2D8y67zncuDQ7SyKrGYeoofqAXN7gqEXjAwZaYEgTveK

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
