### ISSUE TITLE
Validator nadyatar created

### ISSUE THREAD

**Issue by ivangrapher** [near/stakewars-iv#100]
My pool: nadyatar.pool.statelessnet
transaction: https://legacy.explorer.statelessnet.near.org/transactions/6fY4UoZKwQrGqRJnG1NoDfHqz8uNfbhc2Q32oWgBiCUD
our team launched 1 node. The node is located in Germany. If everything works out, we will try to launch more nodes
Our team has been working with nodes for 4 years now. We currently have 20 mainnet networks. We want to install as many as possible.

**Comment by telezhnaya** [comment]
Hey @ivangrapher! 
Congrats, `nadyatar.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/36hnfqij7mwjei1b1S1qB478fAFnge1ACbKDkqu1xSJ3

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
