### ISSUE TITLE
Validator tarabukin.statelessnet

### ISSUE THREAD

**Issue by sonofmother739** [near/stakewars-iv#101]
Good day. We want to become a validator. The validator has been installed. The node has been synchronized. The pool has been created. The server is in Helsinki
https://legacy.explorer.statelessnet.near.org/transactions/BM7QXuf5EfwtnQapSJFQf6ANJUkq2eQbABDfDo1dyyJ6?query=tarabukin.statelessnet

**Comment by sonofmother739** [comment]
form filled

**Comment by telezhnaya** [comment]
Hey @sonofmother739! 
Congrats, `tarabukin.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/CHBBjN973RFUGXGUo2cC2CLykR2R3mwMh5Y8g4WEEVAu

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
