### ISSUE TITLE
Becoming a Validator Proposal for teenu4.pool.statelessnet

### ISSUE THREAD

**Issue by teenu4** [near/stakewars-iv#104]
### How many nodes do you plan to run?
1

### Why do you want to run a validator node on StatelessNet?
I'm already working as a validator in other networks, I'm interested to work with Near as well

### What region(s) do you plan to run on?
Finland, Europe. Please let me know if you need any other location.

**Comment by telezhnaya** [comment]
Hey!
You need to create the pool with the instruction https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction

```
Error: TX receiver ID <teenu4.pool.statelessnet> doesn't exist
```

**Comment by teenu4** [comment]
Hi @telezhnaya, 
The pool should be created now, could you please try again now?

**Comment by telezhnaya** [comment]
Hey @teenu4 ! 
Congrats, `teenu4.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/6SDteDhbqNPnjKowQzqv6MbzUPqzThy363xzy8dLuGeB

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
