### ISSUE TITLE
Becoming a Validator Proposal for kokos_sbgid.statelessnet

### ISSUE THREAD

**Issue by KokosP** [near/stakewars-iv#105]
### How many nodes do you plan to run?
1

### Why do you want to run a validator node on StatelessNet?
We already serve many networks as a validator. We are interested in betting Near as a validator. We are already working with the Near node in the Lava Network project as an RPC provider. I would like to consider the project in more detail.

### What region(s) do you plan to run on?
Europe

**Comment by telezhnaya** [comment]
Hey,
Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

**Comment by telezhnaya** [comment]
How can I help you?

**Comment by KokosP** [comment]
> How can I help you?
we get this error
Error: 
   0: Failed to get network config!

Location:
   src/network_for_transaction/mod.rs:39

**Comment by telezhnaya** [comment]
I need more details

https://github.com/near/stakewars-iv/blob/main/HOW_TO.md

Which step are you trying to do right now?

**Comment by telezhnaya** [comment]
Which step leads to the error?

**Comment by KokosP** [comment]
> Which step leads to the error?

Olga thank you very much for your help. We added RPC manually and everything worked. The form has been sent.

**Comment by telezhnaya** [comment]
You need to create the pool with the instruction https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction

**Comment by KokosP** [comment]
> You need to create the pool with the instruction https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction

we created it right away
https://legacy.explorer.statelessnet.near.org/transactions/AaC2UtmP6uCuiHpAz2oKAQnFJjQex9DyRMmY3SX1P7zP

**Comment by telezhnaya** [comment]
Hey @KokosP! 
Congrats, `dnuker.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/CZvzGwkBaqgHRfmJ5Q1nZCFALXDgap9Kyd2F7mCpAq2M

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
