### ISSUE TITLE
Planning to run a node on  statelessnet

### ISSUE THREAD

**Issue by abahmanem** [near/stakewars-iv#11]
### How many nodes do you plan to run?

I plan to run one node. 

I have already ordered an installed the statelessnet near node on it.
I have a node with these specifications : 
64 GB DDR5 ECC RAM
3.8 TB NVMe SSD 
1 Gbit/s bandwidth

*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?

- I plan to use this node for heavy traffic generation to stress-test statelessnet network.

### What region(s) do you plan to run on?

I'm running a node from Switzerland

**Comment by SageVale** [comment]
Why do you need a node for traffic generation? Isn't StatelessNet RPC sufficient to emit transactions?

**Comment by abahmanem** [comment]
I already a running node on mainnet, participated in Stack Wars 3..
I want to to have a running node on StatelessNet and be part of the 2nd stage of this campaign. 
I want to learn about this new network and discover the new features it will bring 
I want also use this node to test the new version of Near Cli..to play with it. 
I have Installed StatelessNet node already , so i will use it also to generate traffic and participate to Stage 1 of this campaign.
I don t want to use my mainnet node for this  to  generate traffic, i neither wan to use and other minimal Vm with Near cli and query the StatelessNet RPC..
I really want to have a whole complete node on StatelessNet to go through the different stages of this campaign
Thank you

**Comment by abahmanem** [comment]
Pool_ID:

"staking_pool_id": "abahmane"

**Comment by telezhnaya** [comment]
Hey @abahmanem!
Congrats, `abahmane.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/6q2iDbyyLAqy3tPEJqyXJQEAdFwYLswaMJ7QNRB66EDb

```
near-js  validators proposals --networkId custom
| Proposal(Accepted) | abahmane.pool.statelessnet   | 100,000,050        | 1       |
```

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
