### ISSUE TITLE
dimasik.statelessnet Validator Proposal

### ISSUE THREAD

**Issue by Dedok1** [near/stakewars-iv#111]
### How many nodes do you plan to run?

I am planing run one node!

### Why do you want to run a validator node on StatelessNet?
I want participate in StatelessNet testnet as validator because I want to help NEAR Protocol be best  and develop.

### What region(s) do you plan to run on?
I am plan run node in FInland

**Comment by telezhnaya** [comment]
Hey,
Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

**Comment by Dedok1** [comment]
> Hey, Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

yes i did

**Comment by telezhnaya** [comment]
Hey @Dedok1! 
Congrats, `dimasik.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/A4hrXz3DYsw7cRFoynGNjhaC5Q7xhcvFDMJXUZwz4bs7

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
