### ISSUE TITLE
Becoming a Validator Proposal

### ISSUE THREAD

**Issue by omelnyk10** [near/stakewars-iv#114]
### How many nodes do you plan to run?

I will run only one Node

### Why do you want to run a validator node on StatelessNet?
I am interested in running a validator node on StatelessNet because it represents the cutting edge of blockchain technology, particularly in terms of scalability and efficiency. Participating in this network will allow me to contribute to the development and testing of innovative solutions aimed at improving blockchain infrastructure. Additionally, it provides an excellent opportunity to engage with the NEAR community, share knowledge, and collaborate on advancing the network's capabilities.

### What region(s) do you plan to run on?
I plan to run the node in Europe.

**Comment by telezhnaya** [comment]
Hey,
You need to create the pool https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction

**Comment by omelnyk10** [comment]
I created the pool, but did not restart the node. Maybe this is the problem

**Comment by telezhnaya** [comment]
I don't see your pool in the proposal

**Comment by telezhnaya** [comment]
Please share it here

**Comment by omelnyk10** [comment]
broken.pool.statelessnet

**Comment by omelnyk10** [comment]
Sorry that I ask you here, but in the form I fill the wrong address for _mainnet account id (required for rewards)_. Can I changed it somewhere ?

**Comment by telezhnaya** [comment]
I'll drop the previous attempt

**Comment by omelnyk10** [comment]
Thanks!

**Comment by omelnyk10** [comment]
I have sent new form

**Comment by telezhnaya** [comment]
Hey @omelnyk10 ! 
Congrats, `broken.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/Ckdw2xhWU5kDaaLeED1dtpZ3aqywHKxeuHBHgaPrQPb2

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
