### ISSUE TITLE
Do0k13 pool Stateless Network proposal June

### ISSUE THREAD

**Issue by Do0k13** [near/stakewars-iv#116]
### How many nodes do you plan to run?
Just One

### Why do you want to run a validator node on StatelessNet?
I want to gain more experience running nodes in Near Protocol, I have been running successfully my node since Stake Wars III (mexa-staking.poolv1.near) and I want to learn about Stateless Network and the new improvements from Near Protocol; I'm a very passionate professional that want to contribute in this testing stage.

### What region(s) do you plan to run on?
Actually I'm using a VPS hosted in Dusseldorf Germany, I live in Mexico and I'm using those servers due the price and stability.

**Comment by telezhnaya** [comment]
> Error: TX receiver ID <do0k13.pool.statelessnet> doesn't exist

**Comment by telezhnaya** [comment]
Please go through the instruction again https://github.com/near/stakewars-iv/blob/main/HOW_TO.md

**Comment by Do0k13** [comment]
Hello, I have created the pool again, can you validate?

signer_id:    do0k13.statelessnet
receiver_id:  pool.statelessnet
actions:
   -- function call:      
                   method name:  create_staking_pool
                   args:         {
                                   "owner_id": "do0k13.statelessnet",
                                   "reward_fee_fraction": {
                                     "denominator": 100,
                                     "numerator": 10
                                   },
                                   "stake_public_key": "ed25519:6fj2KCFhndmZAZEHCKdedABv8zGTZZVkTspUT5yur5B3",
                                   "staking_pool_id": "do0k13"
                                 }
                   gas:          300.0 Tgas
                   deposit:      35 NEAR

▹▸▹▹▹ Signing the transaction with a key saved in legacy keychain ...                                                                                                                                                
Your transaction was signed successfully.
Public key: ed25519:6fj2KCFhndmZAZEHCKdedABv8zGTZZVkTspUT5yur5B3
Signature: ed25519:5dhRmoNHjSr74xZ5QS4QNVy9VhyjHddZr5igXsaH7Skxh6JQ5KfXkncbVes6gjMwsvF8yEvuY11ZdtfHNuLiECj4
--- Logs ---------------------------
Logs [pool.statelessnet]:   No logs
Logs [do0k13.pool.statelessnet]:   No logs
Logs [do0k13.pool.statelessnet]:   No logs
Logs [do0k13.statelessnet]:   No logs
Logs [do0k13.pool.statelessnet]:   No logs
Logs [do0k13.statelessnet]:   No logs
Logs [pool.statelessnet]:
  The staking pool @do0k13.pool.statelessnet was successfully created. Whitelisting...
Logs [whitelist.statelessnet]:   No logs
Logs [do0k13.statelessnet]:   No logs
Logs [do0k13.statelessnet]:   No logs
--- Result -------------------------
true
------------------------------------

The "create_staking_pool" call to <pool.statelessnet> on behalf of <do0k13.statelessnet> succeeded.

Gas burned: 44.7 Tgas
Transaction fee: 0.00043760741120747 NEAR
Transaction ID: J4vdPpdJraegoTZ2D8bYNVuTjiJsAkXWRYQemdnFEVT4
To see the transaction in the transaction explorer, please open this url in your browser:
https://rpc.statelessnet.nearone.org/J4vdPpdJraegoTZ2D8bYNVuTjiJsAkXWRYQemdnFEVT4

▹▹▹▹▸ Sending transaction ...

**Comment by Do0k13** [comment]
near account view-account-summary do0k13.pool.statelessnet network-config statelessnet now
▹▸▹▹▹ Receiving an inquiry about your account ...                                                                                                                                                                    
---------------------------------------------------------------------------------------------------
 do0k13.pool.statelessnet         At block #118997070 
                                  (XuLv3yvutkJyhQyqWX6boudQT9r5Nbxf5vrghaAiEeZ) 
---------------------------------------------------------------------------------------------------
 NEAR Social profile unavailable  The profile can be edited at https://near.social 
                                  or using the cli command: bos social-db manage-profile 
                                  (https://github.com/bos-cli-rs/bos-cli-rs) 
---------------------------------------------------------------------------------------------------
 Native account balance           35.01 NEAR 
---------------------------------------------------------------------------------------------------
 Validator stake                  0 NEAR 
---------------------------------------------------------------------------------------------------
 Storage used by the account      262.5 KB 
---------------------------------------------------------------------------------------------------
 Contract (SHA-256 checksum hex)  fcbcf3f3721d9ca92be6b3ecd109c91909bfc435a969bf4c7c43215be6c4a6b7 
---------------------------------------------------------------------------------------------------
 Access keys                      Account is locked (no access keys) 
---------------------------------------------------------------------------------------------------


Here is your console command if you need to script it or re-run:
    near account view-account-summary do0k13.pool.statelessnet network-config statelessnet now

**Comment by telezhnaya** [comment]
Hey @Do0k13! 
Congrats, `do0k13.pool.statelessnet` is accepted as a validator on StatelessNet.

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
