### ISSUE TITLE
POSTHUMAN pool Stateless Network proposal

### ISSUE THREAD

**Issue by evgen3000** [near/stakewars-iv#118]
### How many nodes do you plan to run?

1

### Why do you want to run a validator node on StatelessNet?

We are validator in Cosmos Ecosystem And we want to scale to "near" network, because it seem interesting, and our delegators want to see us in "near" network

### What region(s) do you plan to run on?

Europe

**Comment by telezhnaya** [comment]
Hey,
Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

**Comment by evgen3000** [comment]
> Hey, Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

Hello! Sorry for delay. Of course we submitted the form

**Comment by telezhnaya** [comment]
Hey @evgen3000! 
Congrats, `posthuman.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/ABxHSRQ2xA4unVHDvgmpQqivmA9cTuWzxqCHNdwMm7na

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
