### ISSUE TITLE
Legends Validator - V2

### ISSUE THREAD

**Issue by Nobody-Inc** [near/stakewars-iv#119]
### How many nodes do you plan to run? Atleast one, but have the ability to run multiple if needed (May do atleast two for failover). 
We have servers is multiple datacentersthat match our mainnet/testnet deployments that we would mimic.  Will be glad to share all specs if interested

**Comment by telezhnaya** [comment]
Hey @Nobody-Inc ! 
Congrats, `legendsv2.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/7wuBa6jTWMNFLJURFg5oQYcbckDMw1ozh7KWVTREggHK

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
