### ISSUE TITLE
Becoming a Validator Proposal snoopfear.pool.statelessnet

### ISSUE THREAD

**Issue by snoopfear** [near/stakewars-iv#122]
## Becoming a Validator Proposal

My mainnet node is snoopfear.poolv1.near
Stakewars node is snoopfear.pool.statelessnet

### How many nodes do you plan to run?
1 or more if need

*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?
I have participated in previous Stakewars, I want to be a part of NEAR, continue to participate in growth and receive rewards of course.

### What region(s) do you plan to run on?
Germany

**Comment by telezhnaya** [comment]
Hey,
Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

**Comment by snoopfear** [comment]
> Hey, Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

Yeah, just now.

**Comment by telezhnaya** [comment]
Please fill it in again
main net account id usually has the format `***.near` and staking pool id on statelessness should be like `***.pool.statelessnet`

**Comment by snoopfear** [comment]
> Please fill it in again main net account id usually has the format `***.near` and staking pool id on statelessness should be like `***.pool.statelessnet`

ohh, sorry, done)

**Comment by telezhnaya** [comment]
Hey @snoopfear! 
Congrats, `snoopfear.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/6JQiafkkfk8iA7EpnAAcyT8kkVUDsjuarEZqKt2WDj62

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
