### ISSUE TITLE
Validator BlockPro

### ISSUE THREAD

**Issue by Shoni-O** [near/stakewars-iv#123]
### How many nodes do you plan to run?
I plan to run one node.

### Why do you want to run a validator node on StatelessNet?
By participating in StatelessNet, I can gain early access to this cutting-edge technology and contribute to testing and improving its functionality. Overall, running a validator node on StatelessNet aligns with my interest in blockchain technology and my desire to be at the forefront of significant advancements in the field.

### What region(s) do you plan to run on?
Finland

**Comment by Shoni-O** [comment]
Stakewars node is block-pro.pool.statelessnet

**Comment by telezhnaya** [comment]
> Error: TX receiver ID <block-pro.pool.statelessnet> doesn't exist

You need to create the pool with the instruction https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction

**Comment by telezhnaya** [comment]
https://legacy.explorer.statelessnet.near.org/transactions/GUhPiZKPho7JkgYiZvtaWVbBvNFLN6UiecbWkSyYUAr3
