### ISSUE TITLE
pampushka becoming a validator proposal

### ISSUE THREAD

**Issue by Pamushka** [near/stakewars-iv#125]
### How many nodes do you plan to run?

I'll run 1 node

### Why do you want to run a validator node on StatelessNet?

I want try new experience: being a validator

### What region(s) do you plan to run on?

Finland

**Comment by telezhnaya** [comment]
Hey @Pamushka! 
Congrats, `pampushka.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/ALLwPFRnJUZrSs5VbVEaJzDV7wGA4kXJEzdibdtzSshE

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
