### ISSUE TITLE
Becoming a Validator Proposal crazydimka.pool.statelessnet

### ISSUE THREAD

**Issue by DmitriiRabeckii** [near/stakewars-iv#126]
## Becoming a Validator Proposal
Stakewars node is crazydimka.pool.statelessnet
### How many nodes do you plan to run?
I plan 1, if necessary, I can do more.
### Why do you want to run a validator node on StatelessNet?
I want to become a part of such a large project as NEAR, and help this Star wars project.
### What region(s) do you plan to run on?
Germany

**Comment by telezhnaya** [comment]
Hey,
Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

**Comment by DmitriiRabeckii** [comment]
> Hey, Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

I have now sent the form

**Comment by telezhnaya** [comment]
Hey @DmitriiRabeckii! 
Congrats, `crazydimka.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/9zqtHqvFJceBiYacWRW3vd8CVtHns5cXwXr73NgyAXSV

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
