### ISSUE TITLE
voreficna.pool.statelessnet proposal

### ISSUE THREAD

**Issue by MaximAntsiferov** [near/stakewars-iv#128]
### How many nodes do you plan to run?
One

### Why do you want to run a validator node on StatelessNet?

I'm a Python Developer, DevOps trainee and blockchain Enthusiast! 
As a NEAR Believer I would like to be a part of Near Ecosystem.
Maybe some day I will become a mainnet validator, but for now I want to join statelessnet testings and dive deeper into the NEAR.

### What region(s) do you plan to run on?
Netherlands

**Comment by telezhnaya** [comment]
Hey @MaximAntsiferov! 
Congrats, `voreficna.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/CmRQ2AALfXV9hGeFsrfqJUM78HXuzwLDWgKnCzSW8wFe

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
