### ISSUE TITLE
Nokogirisrv Becoming a Validator Proposal

### ISSUE THREAD

**Issue by nokogirisrv** [near/stakewars-iv#130]
I am planning to run one node.

I want to run a validator node on StatelessNet to contribute to the decentralization and security of the NEAR Protocol. I'm excited about the technical challenges and innovations StatelessNet offers and see this as an opportunity to deepen my technical expertise. Additionally, I am eager to engage with and support the NEAR community in this cutting-edge development phase.

I am planning to run a node in Germany.

**Comment by telezhnaya** [comment]
Hey @nokogirisrv! 
Congrats, `nokogirisrv.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/7uuQ38YMjQajETC2YWjbDtdmK7FJLt4ZJYtPF5vJWjgf

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
