### ISSUE TITLE
Proposal to Run a Validator Node on StatelessNet

### ISSUE THREAD

**Issue by Victor199712** [near/stakewars-iv#131]
### How many nodes do you plan to run?
I plan to run 1 node.
*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?
I believe in the mission of StatelessNet to contribute to decentralized consensus and security. Running a validator node allows me to participate in securing the network and validating transactions, thereby supporting its integrity and reliability.

### What region(s) do you plan to run on?
Germany

**Comment by telezhnaya** [comment]
Hey,
You need to create the pool https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction
