### ISSUE TITLE
Becoming a Validator Proposal turnmearound

### ISSUE THREAD

**Issue by bohroman37** [near/stakewars-iv#132]
## Becoming a Validator Proposal
turnmearound.pool.statelessnet
### How many nodes do you plan to run?
I have installed 1 node.
### Why do you want to run a validator node on StatelessNet?
I want to run a validator node on StatelessNet to support the network's security and decentralization, contribute to its stability, and earn staking rewards. Additionally, participating in StatelessNet aligns with my interest in innovative blockchain technologies and allows me to be part of a cutting-edge decentralized ecosystem.
### What region(s) do you plan to run on?
My server is located in Germany.

**Comment by telezhnaya** [comment]
Hey @bohroman37! 
Congrats, `turnmearound.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/DejyBJTdLP3F1nNAV974a444orSsoAFYWvdPWqnXQumk

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
