### ISSUE TITLE
Stateless pool Network proposal tayang.statelessnet

### ISSUE THREAD

**Issue by glnkm** [near/stakewars-iv#136]
### How many nodes do you plan to run? 
1

*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?
I tried to become mainnet validator via previous Stake Wars. 
Now its interesting to me to understand NEAR Protocol better

### What region(s) do you plan to run on?
Europe
tayang.pool.statelessnet

**Comment by telezhnaya** [comment]
Hey @glnkm,
I see you haven't provided your mainnet account id
It means you will not receive the rewards in the end
If it's OK - good
If not, please fill in the form again https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

**Comment by telezhnaya** [comment]
I staked to you
https://legacy.explorer.statelessnet.near.org/transactions/6yVDGRzs3EZ22Yi3q9tgnVvCVSRCAMcBnGRXKQBtx7s3

But I'm still waiting for your reply

**Comment by glnkm** [comment]
> I staked to you https://legacy.explorer.statelessnet.near.org/transactions/6yVDGRzs3EZ22Yi3q9tgnVvCVSRCAMcBnGRXKQBtx7s3
> 
> But I'm still waiting for your reply

Form was updated. 
thanks.
