### ISSUE TITLE
superblock.pool.statelessnet

### ISSUE THREAD

**Issue by scriptsag7** [near/stakewars-iv#138]
### How many nodes do you plan to run? 1 node

*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

**Comment by telezhnaya** [comment]
Hey @scriptsag7! 
Congrats, `superblock.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/HiQb4vZj9Sn8KrAfiBaRQz6YUwLpmGL7icGf2n4HEWF3

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
