### ISSUE TITLE
Known issue: state witness size

### ISSUE THREAD

**Issue by pugachAG** [near/stakewars-iv#14]
### Overview

Currently it is possible to send a sequence of transactions that results in very large chunk state witness. Distributing such state witness to chunk validators will take a lot of time, so block producer won't receive endorsements for the chunk in time. This results in a missing chunk and next chunk producer will execute the same receipts repeating the process. 

For more details see https://github.com/near/nearcore/issues/9378

### Impact
This will effectively make the shard unavailable.

**Comment by telezhnaya** [comment]
[Closed this because we have the issue in the nearcore]
