### ISSUE TITLE
shopiakh become a validator proposal

### ISSUE THREAD

**Issue by ShopiakH** [near/stakewars-iv#144]
### How many nodes do you plan to run?

*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

**Comment by ShopiakH** [comment]
> f you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.

**Comment by ShopiakH** [comment]
1)Just one node
2) I want test this technology and be a part of team who develop this technology
3) Finland

**Comment by telezhnaya** [comment]
Hey @ShopiakH! 
Congrats, `shopiakh.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/95uLptviXkdNyhcaKpUeCgDFQJfHtSc5xCJaHn5GtXkW

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
