### ISSUE TITLE
Become a validator - logiclynx

### ISSUE THREAD

**Issue by LogicLynx209** [near/stakewars-iv#148]
### How many nodes do you plan to run?

1

### Why do you want to run a validator node on StatelessNet?

To ensure my node setup is robust and secure before mainnet deployment.

### What region(s) do you plan to run on?

I'll run my node in Falkenstain, Germany

**Comment by telezhnaya** [comment]
Hey @LogicLynx209! 
Congrats, `logiclynx.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/5V82wijLLM82Z3Yzjyu5JJbLr17Xt3zZs6aG9JJQX7KY

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
