### ISSUE TITLE
vladzte validator proposal

### ISSUE THREAD

**Issue by vlad-zte** [near/stakewars-iv#149]
### How many nodes do you plan to run?
1

*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?
I'm interested in testing new nodes. and deal with possible problems. and I have never had a validator node in near. I'd like to try it

### What region(s) do you plan to run on?
germany

**Comment by telezhnaya** [comment]
Hey @vlad-zte! 
Congrats, `vladzte.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/G6HiW5UfVhEFKCiv5WkjinByt38658VHiHb6QKcxL63w

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
