### ISSUE TITLE
dataguru.pool.statelessnet

### ISSUE THREAD

**Issue by DataGuru74965** [near/stakewars-iv#150]
### How many nodes do you plan to run?

I plan to run 1 node

### Why do you want to run a validator node on StatelessNet?

I run my node to explore NEAR’s account model and its unique features

### What region(s) do you plan to run on?

My node located in Germany

**Comment by telezhnaya** [comment]
Hey @DataGuru74965! 
Congrats, `dataguru.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/QoxYmP28ptGBfXaFnpL84nTV221Xy6iSyWFMtgY9Hn7

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
