### ISSUE TITLE
Becoming a Validator Proposal for `secure.pool.statelessnet`

### ISSUE THREAD

**Issue by foxreymann** [near/stakewars-iv#151]
### How many nodes do you plan to run?

One. 

P.S. I'm opened start a second one if NEAR team wants to test other locations, special circumstances etc.

### Why do you want to run a validator node on StatelessNet?

I want to run a mainnet validator. I treat running StatelessNet validator as an incentivised learning step.

### What region(s) do you plan to run on?

Germany (Hetzner, Data Center Park Falkenstein)

**Comment by ju3tin** [comment]
Sounds great can't wait to stake with you on mainnet

**Comment by desmodrone** [comment]
Looking forward to seeing your validator up and running @foxreymann
