### ISSUE TITLE
OlehAndry becoming a validator proposal

### ISSUE THREAD

**Issue by OlehAndry** [near/stakewars-iv#152]
### How many nodes do you plan to run?
Only one

### Why do you want to run a validator node on StatelessNet?
I thing that StatelessNet  tchnology will have a big future and i Would love to be a part of this.

### What region(s) do you plan to run on?
Europe, Finland

**Comment by telezhnaya** [comment]
You need to create the pool with the instruction https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction

**Comment by OlehAndry** [comment]
> You need to create the pool with the instruction https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction
Ok, thank you.
Done. https://legacy.explorer.statelessnet.near.org/accounts/oleh.pool.statelessnet

**Comment by telezhnaya** [comment]
Hey @OlehAndry! 
Congrats, `oleh.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/5XUMkEFAjzZHC5Wb4hJUAdkBgjQpEixwgndDfdSWepu5

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
