### ISSUE TITLE
ashihara.pool.statelessnet

### ISSUE THREAD

**Issue by ashihara15** [near/stakewars-iv#153]
Becoming a Validator Proposal
How many nodes do you plan to run? 1 node
Why do you want to run a validator node on StatelessNet? I love being a validator.
What region(s) do you plan to run on? USA

**Comment by telezhnaya** [comment]
Hey @ashihara15,
I see you haven't provided your mainnet account id
It means you will not receive the rewards in the end
If it's OK - good
If not, please fill in the form again https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

**Comment by telezhnaya** [comment]
I staked to you
https://legacy.explorer.statelessnet.near.org/transactions/44hBv5k3zz9S3U2noz4qgYiyK8j1SBkFGxFuaQsZnm2J

But I'm still waiting for your reply
