### ISSUE TITLE
Becoming a Validator Proposal from Gem Validator

### ISSUE THREAD

**Issue by GemValidator** [near/stakewars-iv#154]
### How many nodes do you plan to run?
I am planning to run 1 node

### Why do you want to run a validator node on StatelessNet?
I want to run a validator node on StatelessNet to contribute to the security and decentralization of the NEAR blockchain, ensuring its integrity and resilience. This opportunity allows me to deepen my technical expertise in blockchain technology and engage with the NEAR community, fostering innovation and collaboration. Additionally, participating in the testnet phase is enhancing my understanding and involvement in the NEAR.

### What region(s) do you plan to run on?
My server for near would be located in:
Country: United States of America
State: Ohio
City: Cincinnati

**Comment by telezhnaya** [comment]
Hey @GemValidator! 
Congrats, `gemvalidator.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/5X3GvMfh49G7VPpdtGhBgGwKHMvDV82XFWh7ecHS116u

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
