### ISSUE TITLE
web34ever pool Stateless Network proposal

### ISSUE THREAD

**Issue by web3validator** [near/stakewars-iv#155]
### How many nodes do you plan to run?
1
*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?
Our team validates a huge number of [mainnets](https://github.com/web3validator/web34ever-identity/blob/main/web34ever-self-identity.md) and participates in various testnet programs. We are very interested in projects in which we can contribute and gain/give additional knowledge. 

### What region(s) do you plan to run on?
Warsaw, Poland

**Comment by telezhnaya** [comment]
Hey @GemValidator! 
Congrats, `web34ever.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/72zeAgryFQukEoX476eJfma8FD9z9TKPnypg5dTMZR2T

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).

**Comment by web3validator** [comment]
Thank you very much
