### ISSUE TITLE
coderunner.statelessnet

### ISSUE THREAD

**Issue by divaLinJs** [near/stakewars-iv#156]
### How many nodes do you plan to run?
1
*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?
I'm interested in your project. I'm interested in the NEAR ecosystem. I want to be useful and immerse myself in NEAR! Thank you.
### What region(s) do you plan to run on?
Germany

**Comment by telezhnaya** [comment]
Hey @divaLinJs! 
Congrats, `coderunner.pool.statelessnet` is accepted as a validator on StatelessNet.

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
