### ISSUE TITLE
nodeADDICT Validator becoming-a-validator-proposal

### ISSUE THREAD

**Issue by iADDICTi** [near/stakewars-iv#160]
### How many nodes do you plan to run?
One

### Why do you want to run a validator node on StatelessNet?
I am an independent validator, interested in the development of the crypto industry. I am interested in various blockchains and validator nodes. And if you do something that you like and allows you to earn money, it's especially great.

### What region(s) do you plan to run on?
EU

**Comment by telezhnaya** [comment]
Hey,
Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

**Comment by iADDICTi** [comment]
> Hey, Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

Hi! Yes, I have filled it out now :)

Staking pool ID:
node_addict.pool.statelessnet

**Comment by telezhnaya** [comment]
Hey @iADDICTi ! 
Congrats, `node_addict.pool.statelessnet` is accepted as a validator on StatelessNet.

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
