### ISSUE TITLE
Becoming a Validator Proposal cheder.pool.statelessnet

### ISSUE THREAD

**Issue by Yuriychernoivanov** [near/stakewars-iv#162]
## Becoming a Validator Proposal
cheder.pool.statelessnet

### How many nodes do you plan to run?
I have 1 node.

### Why do you want to run a validator node on StatelessNet?
I'm interested in the Near blockchain. And I am committed to launching a validator node to maintain security, stability and decentralization of the network. I have great experience in installing and maintaining servers. And also receive rewards.

### What region(s) do you plan to run on?
Europe

**Comment by telezhnaya** [comment]
Hey @Yuriychernoivanov! 
Congrats, `cheder.pool.statelessnet` is accepted as a validator on StatelessNet.

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
