### ISSUE TITLE
Becoming a Validator Proposal deeploidok.pool.statelessnet

### ISSUE THREAD

**Issue by alexbriks97** [near/stakewars-iv#164]
## Becoming a Validator Proposal
Stakewars node is deeploidok.pool.statelessnet
### How many nodes do you plan to run?
I plan 1
### Why do you want to run a validator node on StatelessNet?
Running a validator node on StatelessNet offers me the opportunity to actively participate in the development and growth of a promising blockchain ecosystem. I am excited about StatelessNet's unique stateless architecture, which has the potential to address current scalability issues, and I want to be part of this groundbreaking solution by ensuring the network's integrity and performance.
### What region(s) do you plan to run on?
Finland

**Comment by telezhnaya** [comment]
Hey @alexbriks97! 
Congrats, `deeploidok.pool.statelessnet` is accepted as a validator on StatelessNet.

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
