### ISSUE TITLE
Becoming a Validator Proposal mememe.pool.statelessnet

### ISSUE THREAD

**Issue by y-selivanova832461897** [near/stakewars-iv#165]
## Becoming a Validator Proposal
Stakewars node is mememe.pool.statelessnet
### How many nodes do you plan to run?
I install only 1
### Why do you want to run a validator node on StatelessNet?
I want to run a validator node on StatelessNet because I am passionate about supporting decentralized networks and believe in the innovative approach StatelessNet takes towards blockchain scalability. Running a validator node allows me to contribute to the network's security and stability while gaining firsthand experience with cutting-edge technology.
### What region(s) do you plan to run on?
Server in Germany

**Comment by telezhnaya** [comment]
Hey @y-selivanova832461897! 
Congrats, `mememe.pool.statelessnet` is accepted as a validator on StatelessNet.

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
