### ISSUE TITLE
theroadz Validator becoming-a-validator-proposal

### ISSUE THREAD

**Issue by ryssroad** [near/stakewars-iv#170]
### How many nodes do you plan to run?
one
*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?
I am an independent validator with an interest in the development of the crypto industry. Furthermore, if one is able to engage in a task that one finds enjoyable and that also allows one to earn money, this is particularly beneficial.
### What region(s) do you plan to run on?
Europe

**Comment by ryssroad** [comment]
Filled the form
`https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg`

**Comment by telezhnaya** [comment]
You need to create the pool with the instruction https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction

**Comment by ryssroad** [comment]
pool created: theroadz.statelessnet

**Comment by telezhnaya** [comment]
This is not a pool
Please read the instruction carefully

**Comment by ryssroad** [comment]
I'm sorry, that pool
https://legacy.explorer.statelessnet.near.org/accounts/theroadz.pool.statelessnet

**Comment by telezhnaya** [comment]
Hey @ryssroad! 
Congrats, `theroadz.pool.statelessnet` is accepted as a validator on StatelessNet.

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
