### ISSUE TITLE
cyberG Validator Node on StatelessNet proposal

### ISSUE THREAD

**Issue by aicyberg** [near/stakewars-iv#172]
### How many nodes do you plan to run?
1
### Why do you want to run a validator node on StatelessNet?
Our team has experience participating in testnets since 2019. We have long wanted to take part in Stake Wars and will try to show good results.
https://github.com/Distributed-Validators-Synctems/Self-Identity/blob/main/cyberG.md
### What region(s) do you plan to run on?
Europe

**Comment by telezhnaya** [comment]
Hey,
Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform
