### ISSUE TITLE
anas validator request dep

### ISSUE THREAD

**Issue by NastyaNFT** [near/stakewars-iv#176]
### How many nodes do you plan to run? 

It`s m one validator!

### Why do you want to run a validator node on StatelessNet?
That`s new knowless for me!

### What region(s) do you plan to run on?
Germany

**Comment by Ckoozzzu** [comment]
@telezhnaya Hi, when will the deposit be sent to me?

**Comment by telezhnaya** [comment]
Hey,
Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

**Comment by NastyaNFT** [comment]
> Hey, Have you filled in the form? https://docs.google.com/forms/d/e/1FAIpQLScmgfOdsxV7c5u4fArn79JBf2MBwFqPIqCVU1x0lAYaZoYuxg/viewform

Hi, right!
my email is:
nastyaborodavich@gmail.com

**Comment by telezhnaya** [comment]
We've hit the limit of 100 participants. Unfortunately, we no longer onboard new validators.
Thank you for your readiness to participate!
Stay tuned for our next programs, we'll announce them in [our social media](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#6-support-channels).
