### ISSUE TITLE
makar228.pool.statelessnet

### ISSUE THREAD

**Issue by Mamba2223** [near/stakewars-iv#177]
Hello, I’m going to run one node, I really want to participate in the testnet of your project. I sympathize with the ideas and goals of your project. I plan to work in the germany.

**Comment by telezhnaya** [comment]
Hey @Mamba2223! 
Congrats, `makar228.pool.statelessnet` is accepted as a validator on StatelessNet.

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running. We recommend you to set up everything ASAP.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
