### ISSUE TITLE
Becoming a Validator Proposal

### ISSUE THREAD

**Issue by dgolovenko511** [near/stakewars-iv#179]
## Becoming a Validator Proposal
golova.pool.statelessnet

### How many nodes do you plan to run?
one node

### Why do you want to run a validator node on StatelessNet?
I have been interested in becoming a NEAR network validator for a long time.

### What region(s) do you plan to run on?
Europe

**Comment by telezhnaya** [comment]
We've hit the limit of 100 participants. Unfortunately, we no longer onboard new validators.
Thank you for your readiness to participate!
Stay tuned for our next programs, we'll announce them in [our social media](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#6-support-channels).
