### ISSUE TITLE
Build DAO validator node for Stateless Net

### ISSUE THREAD

**Issue by jaswinder6991** [near/stakewars-iv#18]
### How many nodes do you plan to run?
**1**

*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?
**We want to start running a stateless validator on mainnet as soon as it live. Running it on StatelessNet for now would be a good learning experience. We also want to help the protocol team to test this new phase as much as we can. We also intend to participate in traffic generation as well. Build DAO is a community led DAO helping to onboard more developers to all aspects of NEAR technology. Participating in the Stake wars is also our attempt to increase our expertise in node infrastructure.**

### What region(s) do you plan to run on?
**Germany**

**Comment by jaswinder6991** [comment]
Staking pool - builddao.pool.statelessnet

**Comment by telezhnaya** [comment]
Hey @jaswinder6991!
Congrats, `builddao.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/BUTtMaD3BS8corh3BJviWj7TvZSN12pfLmDCj8ewgXQq

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
