### ISSUE TITLE
NODERS[TEAM] Validator Node on StatelessNet proposal

### ISSUE THREAD

**Issue by vbloher** [near/stakewars-iv#181]
### How many nodes do you plan to run?

1 node

### Why do you want to run a validator node on StatelessNet?

We would like to participate in the StatelessNet because we're really impressed with your project and eager to support your efforts in building the NEAR ecosystem. We are a legally registered company of professional validators and web3 developers.

Here’s how we can contribute:
- Validate your network, leveraging our experience with Sui, Celestia, Dymension, and 25 other blockchains.
- Develop the NEAR CommunityApp, featuring an Ecosystem Library, Academy, and DevTools (an example of our contribution to Celestia can be seen here: https://celestiahub.org).
- Expand and manage your communities, both online and offline.
- Create DevTools tailored for validators and developers of NEAR.

### What region(s) do you plan to run on?

We plan to deploy our node in Europe; however, if necessary, we can deploy a node in any other region of the world.

**Comment by telezhnaya** [comment]
We've hit the limit of 100 participants. Unfortunately, we no longer onboard new validators.
Thank you for your readiness to participate!
Stay tuned for our next programs, we'll announce them in [our social media](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#6-support-channels).
