### ISSUE TITLE
nodes swap not working 

### ISSUE THREAD

**Issue by abahmanem** [near/stakewars-iv#182]
### Overview
*Please share high level description of the issue/bug you are reporting.*

Node abahmane.pool.statelessnet was working fine, but had issues forcing me to reboot it every  2 days 
so i wanted to change it to a new server

I installed the new node
got the snapshot :  2024-07-11T17:35:38Z on the new server.

swaped the key files : node_key.json and validator_key.json.

Stopped and restarted the 2 nodes.

The new node never catches up , i run it for 2 hours and still getting : 

```
INFO stats: #119903798 Downloading blocks 0.00% (5664 left; at 119903798) 63 peers ⬇ 1.23 MB/s ⬆ 138 kB/s 0.00 bps 0 gas/s CPU: 19%, Mem
 2024-07-11T21:27:37.550973Z  WARN chunks: Error processing partial encoded chunk: ChainError(InvalidChunkHeight)
2024-07-11T21:27:37.550973Z  WARN chunks: Error processing partial encoded chunk: ChainError(InvalidChunkHeight)

11 21:44:37 Ubuntu-2204-jammy-amd64-base neard[10021]: 2024-07-11T21:44:37.417932Z  WARN chunks: Error processing partial encoded chunk: ChainError(InvalidChunkHeight)
Jul 11 21:44:37 Ubuntu-2204-jammy-amd64-base neard[10021]: 2024-07-11T21:44:37.771937Z  WARN chunks: Error processing partial encoded chunk: ChainError(InvalidChunkHeight)
Jul 11 21:44:37 Ubuntu-2204-jammy-amd64-base neard[10021]: 2024-07-11T21:44:37.775546Z  WARN chunks: Error processing partial encoded chunk: ChainError(InvalidChunkHeight)
Jul 11 21:44:37 Ubuntu-2204-jammy-amd64-base neard[10021]: 2024-07-11T21:44:37.779167Z  WARN chunks: Error processing partial encoded chunk: ChainError(InvalidChunkHeight)
.....
```
the old node works fine with the test.near keys.
**But he weird thing is that when** i put my keys back into the old node, i have the same problem as in the new one and the same errors and the old node never catches up

### Affected parties
*Who is affected? Validators? Contract developers? Or regular users?*

abahmane.pool.statelessnet

### Impact
*What’s the worst outcome of the issue?*

the weird thing is that when i put my keys back into the old node, i have the same problem and the same errors and old node never catches up

## Reproduction steps
*Please share step by step guideline on how to reproduce the issue.*

### [Optional] Code reference
*Please locate the issue in the codebase.*

### [Optional] Root cause analysis
*This section is optional but should be filed to claim additional reward.*
*Please share your analysis on the root cause of the issue.*

### [Optional] Suggested fix
*This section is optional but should be filed to claim additional reward.*
*Please share a recommended long-term/short-term fix for the issue.*

**Comment by abahmanem** [comment]
i tried with 3 snapshots : 
2024-07-11T17:35:38Z/ (was the latest when i installed new node)
one from 2024-07-09
one from 2024-07-10

None of the 3 fixed it, i still continued to get the logs above..and the 2 nodes (old and new) never caught up to tip..

Then i tried this one : 2024-07-11T20:35:25Z/ and  the new node (and the old too) managed to  catch up with my keys. 

seems to be a problem of datas

**Comment by staffik** [comment]
Answered in TG: https://t.me/near_stake_wars/3891 and https://t.me/near_stake_wars/3895.
