### ISSUE TITLE
PandaTeam Validator

### ISSUE THREAD

**Issue by DDeAlmeida** [near/stakewars-iv#19]
### How many nodes do you plan to run?
1

*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?
Trying this new feature, helping community when goes live on Mainnet.

Currently mainnet validator: PandaTeam
Community helper for validator, @gmilescu can confirm

### What region(s) do you plan to run on?
Europe

**Comment by telezhnaya** [comment]
Hey!
Could you please create staking pool?
https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction

**Comment by DDeAlmeida** [comment]
Sure, will be up today

**Comment by DDeAlmeida** [comment]
pandateam.pool.statelessnet is up ;)

**Comment by telezhnaya** [comment]
Hey @DDeAlmeida!
Congrats, `pandateam.pool.statelessnet ` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/BagdWZgggzZC8AwhCJ5JHRoEakVwCcuaujyU2h9TzKkH

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).

**Comment by DDeAlmeida** [comment]
Eligible yes as i run PandaTeam.poolv1.near
Everything is ready from my side.
See you in Telegram
