### ISSUE TITLE
I love NEAR

### ISSUE THREAD

**Issue by sashaarch** [near/stakewars-iv#20]
### How many nodes do you plan to run?

1

### Why do you want to run a validator node on StatelessNet?

I would like to run a validator node on StatelessNet for several reasons. Firstly, I am interested in exploring new blockchain technologies and participating in innovative ecosystems. Learning about StatelessNet from Ilya's interview on the "Слезы Сатоши" channel sparked a genuine interest in this testnet for me. My involvement in various testnets over the years has allowed me to appreciate the value of such initiatives and their potential in shaping future blockchain solutions.

Secondly, participating in projects like StatelessNet provides a unique opportunity to understand and test new concepts, such as sharding, which may be key to the future development of blockchain protocols. Even if the likelihood of receiving delegation from the team to run a validator in the mainnet is extremely low, I believe that the experience of participating in such a significant testnet can bring valuable knowledge and experience for my personal and professional growth.

Thus, my interest in running a validator node on StatelessNet combines a desire to explore new technologies, a commitment to professional development in the blockchain field, and respect for initiatives that promote innovation in this space.

### What region(s) do you plan to run on?
I myself live in Uzbekistan and primarily rent servers in Germany, but if necessary, I can rent a server in another country required for the project.

**Comment by telezhnaya** [comment]
Hey!
Could you please create staking pool?
https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction

**Comment by telezhnaya** [comment]
Feel free to open it back if you are still ready to participate
If you are an active mainnet validator at least since March 1st 2024, you are still applicable for partial rewards: https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-available-for-stage-2
