### ISSUE TITLE
GateOmega Validator

### ISSUE THREAD

**Issue by Sato-Loki** [near/stakewars-iv#22]
### How many nodes do you plan to run?
1

*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?
Contribute, support the chain  and  get ready for upcoming changes

### What region(s) do you plan to run on?
USA

**Comment by telezhnaya** [comment]
Hey @Sato-Loki!
Congrats, `gateomega.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/6WoYVz1ZsXCK4JmdPSAJLVwTBnfmEhzK2PVhPXz48Dy1

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
