### ISSUE TITLE
Lovali validator

### ISSUE THREAD

**Issue by baldator** [near/stakewars-iv#23]
### How many nodes do you plan to run?

1

### Why do you want to run a validator node on StatelessNet?

Lovali is willing to help the ecosystem to test stateless validation and help NEAR to take scalability to the next level. We are here to support not only by running a validator but also by generating traffic and test the network.

### What region(s) do you plan to run on?

Switzerland

**Comment by telezhnaya** [comment]
Hey!
You need to create staking pool 
https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction

**Comment by telezhnaya** [comment]
Hey @baldator !
Congrats, `lovali.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/FUC6EWXwsd2fUqDY99pBgaichtwunynQjAaESSzeeGDW

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
