### ISSUE TITLE
SmartMove Validator

### ISSUE THREAD

**Issue by SmartMoveTeam** [near/stakewars-iv#27]
### How many nodes do you plan to run?

1

### Why do you want to run a validator node on StatelessNet?
I am a crypto enthusiast, and I participated in the Stake Wars III program, under mainnet validator name: smartnode.poolv1.near.

Since I am a convinced crypto decentralization advocate, I want to participate and contribute to the Stake Wars IV program, and run a validator node on StatelessNet.

### What region(s) do you plan to run on?
Europe

**Comment by telezhnaya** [comment]
Hey @SmartMoveTeam!
Congrats, `smartmove.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/JShDg94saW5gL6bZW6AHDpXotMy1MQR5yKPHc1ZqqcH

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
