### ISSUE TITLE
Sending of transactions on continual basis

### ISSUE THREAD

**Issue by bluebleublack** [near/stakewars-iv#28]
### Overview

*Overview of the test plan and what type of traffic the participant aims to generate.*
Aim to generate continually random transactions of NEAR towards different accounts - may also try numbers with larger decimal numbers to test accuracy
May also try to try to increase load to RPCs by including looking up past transaction hashes and account balances

### Target traffic volume
5-6 transactions per minute. Would spread transactions across multiple addresses. Frequency can be increased if transactions will be successful
Aim for around 10 look ups of transaction hashes/account balance per minute per account.

*What is the estimated traffic volume?*  I'm unsure which method to measure volume by, but if transactions per minutes - around 5-6 per minute per account, can aim for more
*Don't forget to mention required tokens needed to generate the traffic for the agreed time*  - it depends on the NEAR gas cost - based on testnet NEAR fees may need around 0.4-0.5 NEAR for fees per day for each server I run script on. Plus would need extra NEAR for each of the addresses I plan to spread transactions across. 
*Traffic should be large enough to prove/challenge scalability/stability of the network.*

### Reproduction steps

*Provide us with necessary scripts/codes (in case the engineering team needs to replay in the future)* - can provide my workings if needed

**Comment by staffik** [comment]
@bluebleublack Thank you for submitting this proposal. Could you provide more details what transactions are you proposing to run? If random, how would you generate them? Why only 5-6 transactions per minute?

**Comment by walnut-the-cat** [comment]
To add on what @staffik mentioned, the major goal of traffic generation program is to test realistic threshold of the network. 

If you observe failure point with 5-6 txns per minute, that should be considered as a bug and we highly recommend you to submit such report via bug bounty program. :)

**Comment by bluebleublack** [comment]
@walnut-the-cat Haha I would agree - if couldn't do 5-6 tx a minute would be a bug!

@staffik I guess I was only doing 5-6 transactions a minute to not stress out my cpus and don't want to be mistakened for spamming. But I guess can ramp it up - guess I could run 2-3 transactions every block. I would be basing what transactions I could do on the current NEAR wallet testnet.

Guess in terms of randomness it wouldn't be truly random addresses but rather having the near token send/receive transactions sent at random selection of pre made addresses. Also not sure if doing gasless calls like check state of addresses would be of any worth.

**Comment by walnut-the-cat** [comment]
Hi @bluebleublack , based on the provided information, the current proposal does not seem valid for couple reasons:
* Simple token transfers from account A to B at high volume is something the team has been conducting at regular basis (as it's one of the most common use cases)
* The goal of the program is to test maximal throughput capacity. In other words, we are looking for a proposal that can generate _at least several hundred transaction per second_. 

If you have an idea to update your proposal, we are happy to work with you. Thanks!

**Comment by bluebleublack** [comment]
@walnut-the-cat @staffik That's fine with me, all good. If I think of something then I'll come back. Otherwise best of luck.
