### ISSUE TITLE
Blockscope.net Validator Proposal

### ISSUE THREAD

**Issue by packetstracer** [near/stakewars-iv#30]
### How many nodes do you plan to run?
1

### Why do you want to run a validator node on StatelessNet?
Want to support Near project and get used to the new things related to validating on Staless net.

### What region(s) do you plan to run on?

Los Angeles (US)

**Comment by telezhnaya** [comment]
Hey @packetstracer !
Congrats, `blockscope.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/9U7ZudUkXfyFbtvioASV54jfmhVDv8io1hak91rSk3gD

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
