### ISSUE TITLE
Insuffisent Ressource

### ISSUE THREAD

**Issue by DDeAlmeida** [near/stakewars-iv#38]
Latest version

Server as Mainnet Pool

![image](https://github.com/near/stakewars-iv/assets/52310650/2f07a389-9ab3-4f8f-9c1a-e669a2af1587)

@telezhnaya

**Comment by telezhnaya** [comment]
Mainnet or statelessnet?
Could you please share the version you've using?

**Comment by DDeAlmeida** [comment]
> Mainnet or statelessnet? Could you please share the version you've using?

This is on statelessnet.

latest version: neard (release trunk) (build 1.36.1-214-g92040b372) (rustc 1.76.0) (protocol 82) (db 38)

Hardware: 
64Gb DDR4
1 Tb Nvme

**Comment by telezhnaya** [comment]
cc @Longarithm @robin-near

**Comment by walnut-the-cat** [comment]
@DDeAlmeida , has this been resolved?

**Comment by DDeAlmeida** [comment]
> @DDeAlmeida , has this been resolved?

I didn't reproduced it anymore

**Comment by robin-near** [comment]
That's strange. The crash seems to have happened between block 113394033 and 113394042, and I noticed that 113394041 and 113394042 are empty blocks. I wonder if they are related. It would make sense if validators failed to validate that chunk for some odd reason.
