### ISSUE TITLE
Morphyd Validator 

### ISSUE THREAD

**Issue by sigrlami** [near/stakewars-iv#39]
### How many nodes do you plan to run?
1 node, id: `morphyd.pool.statelessnet`

### Why do you want to run a validator node on StatelessNet?
I'm interested in running a validator node on StatelessNet primarily to contribute to the testing and enhancement of NEAR blockchain's new sharding capabilities. As someone with broad technical knowledge in Rust and blockchains, I'm excited about the potential of NEAR blockchain and have found it to be a promising platform thus far. By actively participating as a validator, I aim to deepen my understanding of NEAR's infrastructure and protocols, while also leveraging my expertise to potentially contribute back to the community.

### What region(s) do you plan to run on?
USA, FL

**Comment by telezhnaya** [comment]
Hey @sigrlami!
Congrats, `morphyd.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/FC4txCjQFQZeFouN4MTbkafeNztZVRpmiVefB5LgXtcq

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
