### ISSUE TITLE
BrainCord Validator

### ISSUE THREAD

**Issue by BrainCord** [near/stakewars-iv#40]
### How many nodes do you plan to run?

1 node, id: `thebraincord.pool.statelessnet`

### Why do you want to run a validator node on StatelessNet?

I'm looking to get involved with running a validator node on StatelessNet. I'm mostly interested in getting to know how the protocol works and understanding the infrastructure, also want to help with testing and improving near blockchain latest sharding features

### What region(s) do you plan to run on?
Europe

**Comment by telezhnaya** [comment]
Hey @BrainCord !
Congrats, `thebraincord.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/7B1vrQDJLwJY29PvMLKWxYrrDJcAnjLkZUscAWKhjkh6

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
