### ISSUE TITLE
jagon validator

### ISSUE THREAD

**Issue by jaggone** [near/stakewars-iv#46]
### How many nodes do you plan to run?
1

### Why do you want to run a validator node on StatelessNet?
I want to support Near, test new features and see how they work.

### What region(s) do you plan to run on?
Finland, Europe

**Comment by telezhnaya** [comment]
Hey @jaggone ! 
Congrats, `jagon.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/9GoJckmCj97NdQLuJmEpMZqnbpNyB16bBG8sv3Zz7CRm

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
