### ISSUE TITLE
Golden_whale validator

### ISSUE THREAD

**Issue by PhysicalBear** [near/stakewars-iv#47]
My mainnet pool golden_whale.poolv1.near

How many nodes do you plan to run?
I want to run one node. If I get some interesting ideas for testing, I may launch a second node.

Why do you want to run a validator node on StatelessNet?
Participating in testnets is my hobby and a way to contribute to the growth of the network.

What region(s) do you plan to run on?
Central region of Russia

**Comment by telezhnaya** [comment]
Hey @PhysicalBear! 
Congrats, `golden_whale.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/T9hDzVwvSvfvAzQiEpkZ5Db13YUYdqoe7T9mfjMMLWi

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
