### ISSUE TITLE
Frensvalidator: Becoming a Validator Proposal

### ISSUE THREAD

**Issue by VV-Corey** [near/stakewars-iv#49]
### How many nodes do you plan to run?
Just 1 :)

### Why do you want to run a validator node on StatelessNet?
We're very excited about Near and the current developments. After running on the mainnet (frensvalidator.poolv1.near) we now also want to see what's coming up on this cool new Statelessnet.

### What region(s) do you plan to run on?
Finland, Europe

**Comment by telezhnaya** [comment]
Hey @VV-Corey! 
Congrats, `frensvalidator.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/ECAFksEtYt435tnVsVG9MHrBEyzUvtdoPm68xsNf9zvM

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).

**Comment by telezhnaya** [comment]
Done
https://legacy.explorer.statelessnet.near.org/transactions/CUuyzYmmL48fhaMkVxi9F7RZsJqZvZ7LvwYv48HQhgaT
