### ISSUE TITLE
Stakecito: Becoming a Validator Proposal 

### ISSUE THREAD

**Issue by stakecito** [near/stakewars-iv#50]
### How many nodes do you plan to run?

We plan to run 1 node.

### Why do you want to run a validator node on StatelessNet?

We follow Near for a longer time now and ran a validator on several testnets. We are very excited about the project, the ecosystem and the developments. We want to grow our contributions in this regard with community outreach and technical expertise. We are also running a mainnet validator on NEAR (stakecito.poolv1.near). For this, we want to run a validator node on StatelessNet as well, to test further changes, see major upcoming stack changes, proof our infrastructure for the future and to contribute with our long-term validator experience.

### What region(s) do you plan to run on?

Europe, Germany

**Comment by telezhnaya** [comment]
Hey @stakecito ! 
Congrats, `stakecito.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/5N5ccjavj3Z5bypkofdk8jfZRRagqL4pD1E5yZ88FLTy

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
