### ISSUE TITLE
Validator Proposal: ou812.pool.statelessnet

### ISSUE THREAD

**Issue by joesixpack** [near/stakewars-iv#51]
### How many nodes do you plan to run?

One.

### Why do you want to run a validator node on StatelessNet?

Participated in Stake Wars I-III, so why not?

### What region(s) do you plan to run on?

Europe.

**Comment by telezhnaya** [comment]
Hey @joesixpack ! 
Congrats, `ou812.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/9hzJzsSnhaJqwzdRPYTw1CerKeGrxCnGy5RaHXfmcEZe

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
