### ISSUE TITLE
snoopfear as a validator in Stakewars IV

### ISSUE THREAD

**Issue by snoopfear** [near/stakewars-iv#52]
My mainnet node is snoopfear.poolv1.near
Stakewars IV node is snoopfear.pool.statelessnet

I have participated in previous Stakewars, I want to be a part of NEAR, continue to participate in growth and receive rewards of course.

My node is located in Finland

**Comment by telezhnaya** [comment]
Hey @snoopfear! 
Congrats, `snoopfear.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/68yY9MK2wCGRKsDx8JF7LL4R7vG6Et6cRWJeaTBkiGD6

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
