### ISSUE TITLE
Validator proposal

### ISSUE THREAD

**Issue by wackazong** [near/stakewars-iv#53]
### How many nodes do you plan to run?

1

*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?

Gain experience with the new tech

### What region(s) do you plan to run on?

Europe/Switzerland

**Comment by telezhnaya** [comment]
Hey @wackazong,
Please follow the instruction https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction

**Comment by telezhnaya** [comment]
Feel free to open it back if you are still ready to participate.
If you are an active mainnet validator at least since March 1st 2024, you are still applicable for partial rewards: https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-available-for-stage-2
