### ISSUE TITLE
Warning while creating statelessnet staking pool.

### ISSUE THREAD

**Issue by ShaMate256** [near/stakewars-iv#54]
I'm following [stakewars-iv](https://github.com/near/stakewars-iv/tree/main) /HOW_TO.md

while calling create_staking_pool method, I've got a warning like **"You are trying to use the account “solidstate.statelessnet”,** but do not have the credentials locally (network: custom)" but credentials are on place.

**nearsw@smain:~$ near call pool.statelessnet create_staking_pool '{"staking_pool_id": "solidstate", "owner_id": "solidstate.statelessnet", "stake_public_key": "ed25519:FNDFadWJy54Ec6YpkAMEbut2wCRvWjEta8Eho3Hd1Jgq", "reward_fee_fraction": {"numerator": 10, "denominator": 100}}' --accountId “solidstate.statelessnet” --networkId custom --deposit 50 --gas 300000000000000
You are trying to use the account “solidstate.statelessnet”, but do not have the credentials locally (network: custom)**

for ex. while generating the same creds, method submits that **"The account solidstate.statelessnet already has local credentials (network: custom)"**
another credentials check: 
**nearsw@smain:~$ cat ~/.near/validator_key.json
{
  "account_id": "test.near",
  "public_key": "ed25519:FNDFadWJy54Ec6YpkAMEbut2wCRvWjEta8Eho3Hd1Jgq",
  "secret_key": "ed25519:***"**
nearsw@smain:~$ cat ~/.near-credentials/custom/solidstate.statelessnet.json
**{
"account_id":"solidstate.statelessnet",
"public_key":"ed25519:2aDJcAnNbwCotpi2dEZY1peCE81t1Q1WJcsPkuUfzp2V",
"private_key":"ed25519:***"
}**

**Comment by staffik** [comment]
@ShaMate256 Could you try with `--accountId solidstate.statelessnet` instead of `--accountId “solidstate.statelessnet”` ?

**Comment by ShaMate256** [comment]
> @ShaMate256 Could you try with `--accountId solidstate.statelessnet` instead of `--accountId “solidstate.statelessnet”` ?

yes it shows error of calling method.

**Comment by staffik** [comment]
Could you try with  `"stake_public_key": "ed25519: 2aDJcAnNbwCotpi2dEZY1peCE81t1Q1WJcsPkuUfzp2V"`? The one from `~/.near-credentials/custom/solidstate.statelessnet.json`.

**Comment by ShaMate256** [comment]
> stake_public_key": "ed25519: 2aDJcAnNbwCotpi2dEZY1peCE81t1Q1WJcsPkuUfzp2V

nope the same answer You are trying to use the account “solidstate.statelessnet”, but do not have the credentials locally (network: custom)

**Comment by staffik** [comment]
@telezhnaya Can you help with this?
