### ISSUE TITLE
Gritsly - statelessnet validator proposal

### ISSUE THREAD

**Issue by gritsly** [near/stakewars-iv#55]
### How many nodes do you plan to run?

I plan on running only one node, unless the hardware spec i chose which is a bit lower than mainnet turns out to not suffice to keep up with the network, then i might add another one on a higher spec.

I'm curious whether some optimizations i introduced on mainnet will let me lower the specs needed for near - this could be a good chance to verify

### Why do you want to run a validator node on StatelessNet?
See above - plus, more experience is always good. I also wish to support progress in the near ecosystem.
A little marketing for the stake service is also good always.

### What region(s) do you plan to run on?
Currently Germany, i'd consider Poland if i have to spin up a bigger node.

**Comment by telezhnaya** [comment]
Hey @gritsly ! 
Congrats, `gritsly.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/CPPuSu9xcYhkrhk7WuedD3K8HrN5FDzjoEZ6x2vKjFCH

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
