### ISSUE TITLE
Do0k13 pool Stateless Network proposal

### ISSUE THREAD

**Issue by Do0k13** [near/stakewars-iv#56]
### How many nodes do you plan to run? 

Just One

### Why do you want to run a validator node on StatelessNet?

I want to gain more experience running nodes in Near Protocol, I have been running successfully my node since Stake Wars III (mexa-staking.poolv1.near) and I want to learn about Stateless Network and the new improvements from Near Protocol; I'm a very passionate professional that want to contribute in this testing stage.

### What region(s) do you plan to run on?

Actually I'm using a VPS hosted in  Dusseldorf Germany, I live in Mexico and I'm using those servers due the price and stability.

**Comment by telezhnaya** [comment]
Hey! Can you please create the staking pool? https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#43-validator-instruction

**Comment by Do0k13** [comment]
Sure thanks!

**Comment by Do0k13** [comment]
Good day, how can I validate when stake was applied?

**Comment by telezhnaya** [comment]
Hey @Do0k13,
Congrats, `do0k13.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/2hjMpjZFyTC3XqwbHF7WPKJMMUhUAVwFL9bWnCyoLVj5

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2), your node should be active and running starting from March 1st, 2024. We recommend you to set up everything at least a couple of days before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
