### ISSUE TITLE
Lavender.Five Validator Proposal

### ISSUE THREAD

**Issue by dylanschultzie** [near/stakewars-iv#62]
### How many nodes do you plan to run?

1

### Why do you want to run a validator node on StatelessNet?
My team currently operates a mainnet validator, and I would like to keep apprised of what's going on with testnet and know what's coming down the pipeline/how to handle it.

### What region(s) do you plan to run on?
EU-EAST

**Comment by telezhnaya** [comment]
Hey,
Please follow the instruction https://github.com/near/stakewars-iv/blob/main/HOW_TO.md

**Comment by dylanschultzie** [comment]
Thanks @telezhnaya 

I think I misread the stage instructions, though. I thought it was requesting a validator be created *after* March 1st, not before March 1st. That means I will no longer be eligible for rewards, correct?

```
In Stage 2 of the program, participants who run a validator node with high uptime can be rewarded in NEAR tokens. For this reward, only mainnet validators active as of March 1st 2024 are eligible.
```

**Comment by telezhnaya** [comment]
You will be still eligible for the part of the rewards, read more here https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-available-for-stage-2

**Comment by telezhnaya** [comment]
Feel free to open it back if you are still ready to participate.
If you are an active mainnet validator at least since March 1st 2024, you are still applicable for partial rewards: https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-available-for-stage-2
