### ISSUE TITLE
So1m validator proposal

### ISSUE THREAD

**Issue by So1m** [near/stakewars-iv#67]
### How many nodes do you plan to run?
1
### Why do you want to run a validator node on StatelessNet?
I was running my node from start of march. Dunno if i am eligable for a rewards :)
### What region(s) do you plan to run on?
Finland

**Comment by walnut-the-cat** [comment]
Hello @So1m , Have you been running a validator node on MainNet? As the reward payout has been processed for the MainNet validators who participated in StakeWar IV, I want to make sure you were following the Telegram channel for that.

**Comment by So1m** [comment]
Hey, yes. I've got a mainnet node running and following both Telegram Stakewars and mainnet validator channels.

Also i am at Near discord.

**Comment by telezhnaya** [comment]
Hey @So1m,
Your proposal does not meet the criteria https://github.com/near/stakewars-iv/blob/main/REWARDS.md#13-running-a-validator-node-with-high-uptime-available-for-stage-2
You needed to fill in the validator form in the beginning, provide valid statelessnet validator account id, have the statelessnet node running, I needed to stake to your statelessnet validator. The statelessnet node also needed to have a good uptime.
So I have to reject this proposal.

**Comment by So1m** [comment]
My node was stopped. So now i guess, i don't have any proofs it was running since the middle of march. Only proof may be a telegram chat with support and this issue from me -> https://github.com/near/stakewars-iv/issues/65

**Comment by telezhnaya** [comment]
Which statelessnet account id have you used?
