### ISSUE TITLE
Near

### ISSUE THREAD

**Issue by Realamere** [near/stakewars-iv#68]
### Overview

*Overview of the test plan and what type of traffic the participant aims to generate.*

### Target traffic volume

*What is the estimated traffic volume?*  
*Don't forget to mention required tokens needed to generate the traffic for the agreed time*  
*Traffic should be large enough to prove/challenge scalability/stability of the network.*

### Reproduction steps

*Provide us with necessary scripts/codes (in case the engineering team needs to replay in the future)*

**Comment by walnut-the-cat** [comment]
Hi @Realamere , I will close this for now as there was no details provided.
