### ISSUE TITLE
Planning to run a node on statelessnet

### ISSUE THREAD

**Issue by abahmanem** [near/stakewars-iv#71]
### How many nodes do you plan to run?

I plan to run one node.

Node specifications :
64 GB DDR5 ECC RAM
3.8 TB NVMe SSD
1 Gbit/s bandwidth

*If you are willing to run more than 1 node, please share your strategy if you have any. Do you plan to run them with different configuration? How do you plan to compare them? We will be happy if you share any details of your experiments here in the comments.*

### Why do you want to run a validator node on StatelessNet?

* I plan to use this node for heavy traffic generation to stress-test statelessnet network.

### What region(s) do you plan to run on?

* Europe, Geneva

* previous proposal : https://github.com/near/stakewars-iv/issues/11

**Comment by telezhnaya** [comment]
Hey,
Could you please provide staking pool account id? I don't see it in your proposal
You need to create it, the instruction is here https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#staking-the-statelessnet-tokens

**Comment by abahmanem** [comment]
Hello,

I created it yesterday : abahmane.pool.statelessnet

https://legacy.explorer.statelessnet.near.org/transactions/FT6vcX1MCMKmVUWyVqWWrw3XPG42znFkgRELoeNHiEF

**Comment by telezhnaya** [comment]
Hey @abahmanem! 
Congrats, `abahmane.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/8TuRuRWQszFXPG9btPWRhmwZUcBdDcK9BSuStB3me3M9

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
