### ISSUE TITLE
gateomega.statelessnet

### ISSUE THREAD

**Issue by Sato-Loki** [near/stakewars-iv#73]
## Becoming a Validator Proposal
gateomega.statelessnet

### How many nodes do you plan to run? 
1

### Why do you want to run a validator node on StatelessNet?
to contribute testing and get ready for upcoming mainnet updates 

### What region(s) do you plan to run on?
USA

**Comment by telezhnaya** [comment]
Hey,
Could you please provide staking pool account id? I don't see it in your proposal
You need to create it, the instruction is here https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#staking-the-statelessnet-tokens

**Comment by telezhnaya** [comment]
Hey @GateOmega-Gist @Sato-Loki ! 
Congrats, `gateomega.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/2BZPFgcgteVYNTfiNrY3jq2CoGr9A1vR9amDevteJSgT

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
