### ISSUE TITLE
GO2Pro Validator

### ISSUE THREAD

**Issue by GO2Pro** [near/stakewars-iv#74]
### How many nodes do you plan to run?

1

### Why do you want to run a validator node on StatelessNet?

I am a crypto enthusiast, and I participated in the Stake Wars III program, under mainnet validator name: smartnode.poolv1.near.

Since I am a convinced crypto decentralization advocate, I want to participate and contribute to the Stake Wars IV program, and run a validator node on StatelessNet.

Here is the proposal that was previously accepted under the name of SmartMove: https://github.com/near/stakewars-iv/issues/27

### What region(s) do you plan to run on?
Europe

**Comment by telezhnaya** [comment]
Hey @GO2Pro! 
Congrats, `go2pro.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/HWbVmgVQEDmC2g7mc2b5aQBjZ5sfmgyodkoGx6pSUie1

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
