### ISSUE TITLE
Gritsly Validator Proposal Statelessnet

### ISSUE THREAD

**Issue by gritsly** [near/stakewars-iv#78]
### How many nodes do you plan to run?

One node

### Why do you want to run a validator node on StatelessNet?

Help the network and gain more experience for when this hits mainnet

### What region(s) do you plan to run on?
EU

### Staking pool id:
gritsly.pool.statelessnet

**Comment by telezhnaya** [comment]
Hey,
Could you please provide staking pool account id? I don't see it in your proposal
You need to create it, the instruction is here https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#staking-the-statelessnet-tokens

**Comment by gritsly** [comment]
Added. It was missing from the template.

I am still not synced though - working on getting peers right now.

**Comment by gritsly** [comment]
I did edit the original post.

Staking pool id:
gritsly.pool.statelessnet

**Comment by telezhnaya** [comment]
Hey @gritsly! 
Congrats, `gritsly.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/9MkdT7rQVtta9zkZA35bcAUGeDohtcnZY3MAa7H9dnDZ

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
