### ISSUE TITLE
Stakecito Statelessnet Validator Proposal

### ISSUE THREAD

**Issue by stakecito** [near/stakewars-iv#79]
### How many nodes do you plan to run?

One node

### Why do you want to run a validator node on StatelessNet?

Test new Near Versions, better prepare for mainnet upgrades, battle testing staging and release binaries and to support the network with testing new features and finding bugs.

### What region(s) do you plan to run on?

EU

### What region(s) do you plan to run on?

stakecito.pool.statelessnet

**Comment by telezhnaya** [comment]
Hey @stakecito! 
Congrats, `stakecito.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/ywL2bm7zygAyf9GuHcg91sKHktHNixPiRsoezAAy4bG

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
