### ISSUE TITLE
frensvalidator.pool.statelessnet

### ISSUE THREAD

**Issue by VV-Corey** [near/stakewars-iv#80]
### How many nodes do you plan to run?

1

### Why do you want to run a validator node on StatelessNet?

We ran on the previous StatelessNet as well as on the mainnet. We are big fans of near and featuring it frequently on our Podcast & Youtube.

### What region(s) do you plan to run on?

Europe/Finland

Pool ID: frensvalidator.pool.statelessnet

**Comment by VV-Corey** [comment]
Hi, just filled it out now. Didn't realize we had to do it again for the 2nd part of the statelessnet. Kind regards

**Comment by telezhnaya** [comment]
Hey @VV-Corey! 
Congrats, `frensvalidator.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/CxU8vbGRJWVLdpFRNCBvEzN6RrCfiRiZUzAREs3Fe3rT

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
