### ISSUE TITLE
staketake.pool.statelessnet

### ISSUE THREAD

**Issue by StakeTake** [near/stakewars-iv#81]
How many nodes do you plan to run?
1

Why do you want to run a validator node on StatelessNet?
we want to try to take part in this exciting testnet

What region(s) do you plan to run on?
EU

Pool ID: staketake.pool.statelessnet

**Comment by telezhnaya** [comment]
Hey @StakeTake! 
Congrats, `staketake.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/4scAKPXTc39EsbVBYPJ375Gnh6zwLNoEjUj2A6w3e5cR

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
