### ISSUE TITLE
SegmentationFault validator

### ISSUE THREAD

**Issue by shurikv** [near/stakewars-iv#83]
How many nodes do you plan to run?
1

Why do you want to run a validator node on StatelessNet?
I participated in StakeWars III and want to help with testing new feature. My mainnet pool: shurik.poolv1.near

What region(s) do you plan to run on?
Europe (Ukraine)

**Comment by telezhnaya** [comment]
Hey @shurikv! 
Congrats, `segmentationfault.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/7oXiCA4AKi2uYbdNyhGVQ2z1pmsBkQGtRavVhHKz69gD

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
