### ISSUE TITLE
add validator tarab.statelessnet

### ISSUE THREAD

**Issue by tarabukinivan** [near/stakewars-iv#84]
our team launched 1 node. The node is located in Helsinki. If everything works out, we will try to launch more nodes
Our team has been working with nodes for 3 years now. We currently have 15 mainnet networks. We want to install as many as possible.

**Comment by telezhnaya** [comment]
Hey @tarabukinivan ! 
Congrats, `tarab.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/5T8LJX9XXahYU5hBv3vxGLPx9qPSN3Y9q3e5pAdKS7nm

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).

**Comment by tarabukinivan** [comment]
Thanks you!

**Comment by tarabukinivan** [comment]
The validator is missing
Hi! 15-20 hours ago I created a validator and a pool. I suggested staked. And the pool was here near-validator validators network-config statelessnet next
But now it's gone. Where did it go? Pool tarab
