### ISSUE TITLE
Lefey Validator becoming-a-validator-proposal

### ISSUE THREAD

**Issue by Lefey** [near/stakewars-iv#88]
### How many nodes do you plan to run?
One

### Why do you want to run a validator node on StatelessNet?
I am independent validator in cosmos sdk networks, ethereum, and some experiment network and i am intresting how to be a near validator

### What region(s) do you plan to run on?
EU

### Staking pool id:
lefey.pool.statelessnet

**Comment by telezhnaya** [comment]
Hey @Lefey! 
Congrats, `lefey.pool.statelessnet` is accepted as a validator on StatelessNet.
https://legacy.explorer.statelessnet.near.org/transactions/HZyDPFrNgB9oVQLSfSeZBGXkW1Fvwor9JzQYkPBsH2CH

The Core Team may change the amount of stake. Though we guarantee it will be greater than the seat price, so you don't need to worry about this.

If you are eligible for [the rewards](https://github.com/near/stakewars-iv/blob/main/REWARDS.md#5-running-a-node-with-high-uptime-active), your node should be active and running starting from June 12th 2 PM UTC, 2024. We recommend you to set up everything before the program starts to be sure everything works as expected.

If you have any issues with your node, please use [this instruction](https://github.com/near/stakewars-iv/blob/main/HOW_TO.md#node-update). If it does not help, reach out to us [on Telegram](https://t.me/near_stake_wars).
